name: Ununtu-16.04 test

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        php-version: [7.0, 7.1, 7.2]
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run test
      run: composer test-unit
