name: Ununtu-18.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-version: [7.1, 7.2, 8.0, 8.1]
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Run test
      run: composer test-unit
